name: video_player_macos
description: MacOS implementation of the video_player plugin.
version: 2.0.1
homepage: https://github.com/ollydixon/flutter_macos_video_player

flutter:
  plugin:
    implements: video_player
    platforms:
      macos:
        pluginClass: FLTVideoPlayerPlugin
        dartPluginClass: VideoPlayerMacOs

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.8.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: # 5.1.1
    git:
      url: https://github.com/tvip/flutter-plugins.git
      ref: 'tvip-version-2.4.1'
      path: packages/video_player/video_player_platform_interface

dev_dependencies:
  pedantic: ^1.10.0
  pigeon: ^10.0.0
